### ISSUE TITLE
Use different set of icons for development

### ISSUE THREAD

**Issue by sergioalvz** [privacycloud/consent-manager-web-ext#130]
Ey all:

It is quite confusing to have both, the production bundle and the development bundle using the very same icons. I always end up removing the production version to don't mess things up but I would find, at the same time, very convenient to have the ability to have both of them installed in order to spot possible differences.

The simplest approach coming to my mind is by using a different set of icons. Since the extension's icon can be set programmatically, it shouldn't be complex to point to different resources based on the current execution environment.

**Comment by victorpergo** [comment]
@sergioalvz that makes sense. Let me ask for a new set of icons that we can use for development and I'll share them here.

**Comment by dcarral** [comment]
Looking forward to this! 

@sergioalvz maybe we could pair working on this issue? Let's keep in touch ;)

**Comment by victorpergo** [comment]
Here we go with the development icon set. This set of icons respect the same naming / format / size as the ones currently placed in `/app/images` within the project (we've taken those as reference). The development icon set represent only half of the PrivacyCloud crown within the icons so that we can visually differentiate them from the production ones.

[dev-icons.zip](https://github.com/privacycloud/consent-manager-web-ext/files/4031355/dev-icons.zip)
