### ISSUE TITLE
Doesn't seem to do much/doesn't seem to work with most popular consent managers

### ISSUE THREAD

**Issue by atleta** [privacycloud/consent-manager-web-ext#71]
Hi,

So I've been using this for a while but I still keep clicking through these toxic cookie managers to disable all their categories one-by-one. E.g. I just came across this site: https://www.addictivetips.com/ . I'm not able to find the web site for their consent manager, but this one seems to be pretty common.

Which ones do you support? And what does declining consent by ommission mean? Is it simply so that you just hide the dialog hoping that the web site plays along the GDPR rules and does require opt-in (as opposed to opt-out)? I don't think this generally is the case. That's partly the reason why we need an extension like yours. (Also, it would be a great addition to have a report facility for unsupported sites/consent managers.)

**Comment by PrivacyCloudDevelopers** [comment]
Hi!

The extension currently blocks a set of widely used third-party cookie manager providers including TrustArc, Cookie Control and OneTrust. It also blocks self-hosted cookie managers, using patterns to identify and remove HTML elements from specific websites. Consent Manager Extension maintains specific rules in place to remove such elements from some of the top-visited websites (in UK). In the case of https://www.addictivetips.com, it looks like it's using a self-hosted cookie manager, which could be removed adding custom rules.

You are right regarding the meaning of "declining consent by omission". We also agree on thinking that most websites do not play along the GDPR rules today. Due to this, the extension does not actually prevent a site from tracking its users in most cases. However, the purpose of the extension is to remove inconvenient cookie manager windows and also to warn the user by switching the extension icon color to red in the case of a third-party cookie being served after removing the cookie manager window, meaning that the website is not GDPR-compliant.

Thank you for your feedback regarding having a facility for unsupported sites/consent managers! looks like a good idea to let users to participate reporting unsupported cases. In any case we've already added addictivetips.com to our backlog of sites to research on.

The PrivacyCloud team.
